name: Deployment
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    name: Compile application, deploy with ssh and systemd.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
        with: 
          working-directory: signaling-app
      - name: Compile Rust
        run: |
          cargo build +stable --release