name: Deployment
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    name: Compile application, deploy with ssh and systemd.
    runs-on: ubuntu-latest
    env:
      SSH_KEY_PATH: ${{ github.workspace }}/../private.key
      APP_NAME: json-message-relay
    steps:
      - uses: actions/checkout@v2
      
      - uses: Swatinem/rust-cache@v1
      
      - name: Compile Rust
        run: |
          cargo +stable build --release
      
      # Credits https://stackoverflow.com/a/60479844
      - name: Copy SSH key and known hosts
        if: ${{secrets.SSH_PRIVATE_KEY}}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ../private.key
          sudo chmod 600 ../private.key
          ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_HOST: ${{secrets.SSH_HOST}}
      
      - name: Deploy with rsync
        if: ${{secrets.SSH_PRIVATE_KEY}}
        run: | 
          rsync -e "ssh -i $SSH_KEY_PATH" $SSH_USER@$SSH_HOST:/target/release/$APP_NAME /$APP_NAME/
        env:
          SSH_USER: ${{secrets.SSH_USER}}
          SSH_HOST: ${{secrets.SSH_HOST}}
